"""Single source of truth for league configuration.

Draft rules (rounds, flex slots, required categories) and the category alias
lists used to read the ingredient sheet all live in ``league_config.json``.
Every app and tool loads them from here instead of hardcoding — so a new
season or a differently-shaped league is a data edit, not a code change.

The DEFAULTS below intentionally mirror the historical hardcoded values, so
if ``league_config.json`` is missing or partial, behavior is unchanged.
"""
import json
import os

DEFAULTS = {
    "rounds": 7,
    "flex_slots": 3,
    # The ingredient set to draft from. ``ingredients_path`` is authoritative;
    # ``ingredient_year`` is for display/labeling. Defaults mirror historical
    # behavior (2025); the checked-in league_config.json points at the current
    # season so the live app uses it while golden tests keep reading 2025.
    "ingredient_year": 2025,
    "ingredients_path": "ingredients_2025.csv",
    "required_categories": {"Base Malt": 1, "Hop": 1, "Yeast": 1, "Adjunct": 1},
    "category_aliases": {
        "Base Malt": ["Base Malt", "Base Malts", "Base Malts and Extracts"],
        "Hop": ["Hop", "Hops"],
        "Yeast": ["Yeast", "Yeasts"],
        "Adjunct": ["Adjunct", "Adjuncts", "Adjuncts/Spices/Fruits"],
        "Specialty": [
            "Specialty", "Specialty Malt", "Specialty Malts",
            "Specialty Malt and Flaked Grains", "Specialty Malts and Flaked Grains",
            "Flaked Grains", "Flaked/Other Grains",
        ],
        "Extra": ["Extra", "Extras"],
    },
    # Required categories where a *second* pick is almost never useful (a
    # second yeast means co-pitching). The recommender demotes -- never hides --
    # a candidate from these once the roster already holds one; see
    # draft_core.DEFAULT_SQUASH["redundant_mult"].
    "single_pick_categories": ["Yeast"],
    # Second-tier ("workable") style membership -- what might work when the
    # characteristic options are gone. Same shape as style_matrix.json;
    # generated alongside it. Optional.
    "style_matrix_workable_path": "style_matrix_workable.json",
    # Ingredient similarity files (generated by scripts/build_similarity.py),
    # keyed by the style-matrix category they cover. Missing files are
    # tolerated (the corresponding substitution signal is simply off).
    "similarity_files": {
        "Hop": "hop_similarity.json",
        "Yeast": "yeast_similarity.json",
        "Base Malt": "malt_similarity.json",
        "Specialty": "malt_similarity.json",
    },
}

DEFAULT_CONFIG_PATH = "league_config.json"


def load_league_config(path: str = DEFAULT_CONFIG_PATH) -> dict:
    """Return league config, overlaying values from ``path`` onto DEFAULTS.

    A missing or malformed file falls back to DEFAULTS (per key), so partial
    configs are fine and a corrupt file never crashes the app.
    """
    cfg = {k: (v.copy() if isinstance(v, (dict, list)) else v)
           for k, v in DEFAULTS.items()}
    if os.path.exists(path):
        try:
            with open(path) as f:
                overrides = json.load(f)
            if isinstance(overrides, dict):
                cfg.update(overrides)
        except (json.JSONDecodeError, OSError):
            pass  # keep DEFAULTS
    return cfg
